config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

API_URLS = [path("v1/feedback/", include("healthpat.feedback.urls"))]
UI_URLS = [
    path(settings.ADMIN_URL, admin.site.urls),
    # Dashboard
    path("", include("healthpat.dashboard.urls", namespace="dashboard")),
    # Retail
    path("", include("healthpat.retail.urls", namespace="retail")),
    # Users
    path("", include("healthpat.users.urls", namespace="users")),
]
urlpatterns = UI_URLS + API_URLS
if settings.DEBUG:

    # DEBUG ERROR PAGES
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    # DJANGO DEBUG TOOLBAR
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

healthpat/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [path("dashboard", views.DashboardView.as_view(), name="dashboard",)]

healthpat/feedback/urls.py
from django.urls import path

from . import views

app_name = "feedback"
urlpatterns = [
    path(
        "",
        views.FeedbackView.as_view(),
        name="feedback",
    )
]

healthpat/retail/urls.py
from django.urls import path


from . import views

app_name = "retail"
urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("request/", views.RequestNewDrugView.as_view(), name="request"),
]

healthpat/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
)
from . import views

app_name = "users"
urlpatterns = [
    path("signup", views.signup, name="register"),
    path(
        "login",
        views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path("logout", LogoutView.as_view(), name="logout"),
    path(
        "password-reset/",
        views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

healthpat/algolia/models.py
from django.db import models

# Create your models here.

healthpat/currencies/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from crawfish.models import BaseModel


class Currency(BaseModel):

    code = models.CharField(_("Currency Code"), max_length=3, unique=True)
    symbol = models.CharField(_("Symbol"), max_length=1)

    def __str__(self):
        return (
            f"Currency(code: '{self.code}', symbol: '{self.symbol}', "
            f"exchange_rate: '{self.exchangerate_set.order_by('updated_at').first()}')"
        )

    class Meta:
        verbose_name = "Currency"
        verbose_name_plural = "Currencies"


class ExchangeRate(BaseModel):
    usd = models.FloatField(_("USD per"))

    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)

    def __str__(self):
        return f"ExchangeRate(usd: '{self.usd}')"

    class Meta:
        verbose_name = "Exchange Rate"
        verbose_name_plural = "Exchange Rates"

healthpat/dashboard/models.py
from django.db import models

# Create your models here.

healthpat/feedback/models.py
from django.db import models

from crawfish.models import EmailField, BaseModel


class Feedback(BaseModel):
    class Meta:
        verbose_name = "Feedback"
        verbose_name_plural = "Feedback"

    email = EmailField(
        max_length=255,
        unique=False,  # Do not enforce unique email address so as to allow >1 feedback records per email
    )
    message = models.TextField()

    def __str__(self):
        return f"Feedback(email: '{self.email}', message: '{self.message[:10]}')"

healthpat/locations/models.py
from django.db import models

# Create your models here.

healthpat/retail/forms.py
from django import forms
from .models import NewDrugsRequested

from crispy_forms.helper import FormHelper

# New Drug Request Form
class NewDrugRequestForm(forms.ModelForm):
    class Meta:
        model = NewDrugsRequested
        fields = "__all__"

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.label_class = "form-control-label"
        helper.form_tag = False  # Prevent crispy form from adding form tag. We do this manually in HTML to get more control over the submit button.
        return helper

healthpat/users/forms.py
import unicodedata

from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from crispy_forms.bootstrap import PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Div, Field, Layout, MultiField, Submit
from crawfish.emails import send_mail

### LOGIN
class LoginForm(forms.AuthenticationForm):
    prepend_text = {
        # field_name: prepend_text
        "username": "<i class='fa fa-user'></i>",
        "password": "<i class='fa fa-key'></i>",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages.update(
            {
                "invalid_login": _(
                    "Invalid %(username)s or password. Note that both "
                    "fields may be case-sensitive."
                ),
            }
        )
        self.fields["username"].empty_value = "test@example.com"
        self.fields["password"].empty_value = "Password"

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.label_class = "form-control-label"
        helper.form_tag = False  # Prevent crispy form from adding form tag. We do this manually in HTML to get more control over the submit button.
        layout = helper.layout = Layout()
        # Apply placeholders and prepended text to input
        # https://stackoverflow.com/questions/13482753/use-field-label-as-placeholder-in-django-crispy-forms/23971724#23971724

        for field_name, field in self.fields.items():
            item = PrependedText(
                field_name,
                self.prepend_text.get(field_name),
                placeholder=field.empty_value,
            )

            if field_name == "password":
                """Apply the 'lost password' link"""
                item = HTML(
                    """<div class="form-group mb-4">
                      <div class="d-flex align-items-center justify-content-between">
                        <div>
                          <label class="form-control-label">Password*</label>
                        </div>
                        <div class="mb-2">
                          <a tabindex="-1" href="{% url 'users:password_reset' %}" class="small text-muted text-underline--dashed border-primary">Forgot password?</a>
                        </div>
                      </div>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text"><i class="fa fa-key"></i></span>
                        </div>
                        <input type="password" name="password" autocomplete="current-password" class="form-control" id="input-password" placeholder="Password">
                      </div>
                    </div>"""
                )
            layout.append(item)

        return helper


### {end} LOGIN


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = get_user_model()


class EmailField(forms.UsernameField):
    def to_python(self, value):
        return unicodedata.normalize("NFKC", super().to_python(value))

    def widget_attrs(self, widget):
        return {
            **super().widget_attrs(widget),
            "autocapitalize": "none",
            "autocomplete": "email",
        }


class UserCreationForm(forms.UserCreationForm):
    prepend_text = {
        # field_name: prepend_text
        "email": "<i class='fa fa-user'></i>",
        "password1": "<i class='fa fa-key'></i>",
        "password2": "<i class='fa fa-key'></i>",
    }
    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_email": _("This email has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = get_user_model()
        fields = ("email",)
        field_classes = {"email": EmailField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].empty_value = "test@example.com"
        self.fields["password1"].empty_value = "**********"
        self.fields["password2"].empty_value = "**********"

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.label_class = "form-control-label"
        helper.form_tag = False  # Prevent crispy form from adding form tag. We do this manually in HTML to get more control over the submit button.
        layout = helper.layout = Layout()
        # Apply placeholders and prepended text to input
        # https://stackoverflow.com/questions/13482753/use-field-label-as-placeholder-in-django-crispy-forms/23971724#23971724

        for field_name, field in self.fields.items():
            item = PrependedText(
                field_name,
                self.prepend_text.get(field_name),
                placeholder=field.empty_value,
            )

            layout.append(item)

        return helper

    def clean_email(self):
        email = self.cleaned_data["email"]

        try:
            get_user_model().objects.get(email=email)
        except get_user_model().DoesNotExist:
            return email

        raise ValidationError(self.error_messages["duplicate_email"])


class PasswordResetForm(forms.PasswordResetForm):
    prepend_text = {
        # field_name: prepend_text
        "email": "<i class='fa fa-user'></i>",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].empty_value = "test@example.com"

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.label_class = "form-control-label"
        helper.form_tag = False  # Prevent crispy form from adding form tag. We do this manually in HTML to get more control over the submit button.
        layout = helper.layout = Layout()
        # Apply placeholders and prepended text to input
        # https://stackoverflow.com/questions/13482753/use-field-label-as-placeholder-in-django-crispy-forms/23971724#23971724

        for field_name, field in self.fields.items():
            item = PrependedText(
                field_name,
                self.prepend_text.get(field_name),
                placeholder=field.empty_value,
            )

            layout.append(item)
        return helper

    def send_mail(
        self,
        subject_template_name,
        email_template_name,
        context,
        from_email,
        to_email,
        *args,
        **kwargs,
    ):

        template_id = "d-9347c41146c648d08662832c21bee312"  # Password reset template ID

        reset_url = f"""{context.get("protocol")}://{context.get("domain")}{reverse(
            "users:password_reset_confirm",
            kwargs=dict(uidb64=context.get("uid"), token=context.get("token")),
        )}"""
        send_mail(
            to_email=to_email,
            template_id=template_id,
            data={to_email: {"reset_url": reset_url}},
            from_email=from_email,
        )


class SetPasswordForm(forms.SetPasswordForm):
    prepend_text = {
        # field_name: prepend_text
        "new_password1": "<i class='fa fa-key'></i>",
        "new_password2": "<i class='fa fa-key'></i>",
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["new_password1"].empty_value = "**********"
        self.fields["new_password2"].empty_value = "**********"

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.label_class = "form-control-label"
        helper.form_tag = False  # Prevent crispy form from adding form tag. We do this manually in HTML to get more control over the submit button.
        helper.form_show_errors = True
        layout = helper.layout = Layout()
        # Apply placeholders and prepended text to input
        # https://stackoverflow.com/questions/13482753/use-field-label-as-placeholder-in-django-crispy-forms/23971724#23971724

        for field_name, field in self.fields.items():
            item = PrependedText(
                field_name,
                self.prepend_text.get(field_name),
                placeholder=field.empty_value,
            )

            layout.append(item)

        return helper

healthpat/algolia/views.py
from django.shortcuts import render

# Create your views here.

healthpat/currencies/views.py
from django.shortcuts import render

# Create your views here.

healthpat/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView


class DashboardView(LoginRequiredMixin, TemplateView):

    template_name = "dashboard/index.html"
    extra_context = {"header_style": "primary"}

healthpat/feedback/views.py
from rest_framework import permissions
from rest_framework.generics import CreateAPIView

from .serializers import FeedbackSerializer


class FeedbackView(CreateAPIView):

    permission_classes = (permissions.AllowAny,)
    serializer_class = FeedbackSerializer

healthpat/locations/views.py
from django.shortcuts import render

# Create your views here.

healthpat/products/views.py
from django.shortcuts import render

# Create your views here.

healthpat/retail/views.py
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .forms import NewDrugRequestForm


class HomePageView(TemplateView):
    """Render the home page"""

    template_name = "retail/home.html"
    extra_context = {"settings": settings, "header_style": "primary"}


class RequestNewDrugView(SuccessMessageMixin, CreateView):
    """Render a page to collect requests to index new drugs via form submission"""

    template_name = "retail/requests.html"
    extra_context = {"header_style": "primary"}
    form_class = NewDrugRequestForm
    success_url = reverse_lazy("retail:request")
    success_message = "Thanks for your message!"

healthpat/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import views as django_views
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from crawfish.emails import send_mail

from .forms import LoginForm, UserCreationForm, PasswordResetForm, SetPasswordForm


class LoginView(django_views.LoginView):
    extra_context = {"header_style": "primary"}
    form_class = LoginForm
    template_name = "users/login.html"


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Login the new user automatically
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password1")
            new_user = authenticate(username=email, password=password)
            login(request, new_user)
            send_mail(
                to_email=new_user.email,
                template_id="d-114c8baff3f34ade9fe2be663c4bf3f3",
            )
            messages.success(
                request,
                f"Welcome to HealthPat. Check your inbox to confirm your email.",
            )
            return redirect("dashboard:dashboard")
    else:
        form = UserCreationForm()

    return render(
        request, "users/signup.html", {"form": form, "header_style": "primary"}
    )


class PasswordResetView(django_views.PasswordResetView):
    extra_context = {"header_style": "primary"}
    success_url = reverse_lazy("users:password_reset_done")
    template_name = "users/password_reset.html"
    form_class = PasswordResetForm


class PasswordResetDoneView(django_views.PasswordResetDoneView):
    extra_context = {"header_style": "primary"}
    template_name = "users/password_reset_done.html"


class PasswordResetConfirmView(
    SuccessMessageMixin, django_views.PasswordResetConfirmView
):
    success_url = reverse_lazy("users:login")
    success_message = "You may now log in using your new password."
    extra_context = {"header_style": "primary"}
    template_name = "users/password_reset_confirm.html"
    form_class = SetPasswordForm

healthpat/templates/base.html
{% load static i18n compress %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{{ APP_NAME }}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="https://res.cloudinary.com/dmuligbfy/image/upload/r_50/v1607035173/healthpat/favicon.png">

    {% block css %}

      <!-- Font Awesome -->
{#      <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">#}
      <link href="{% static 'libs/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
      <!-- Libs CSS -->
      <link rel="stylesheet" href="{% static 'libs/@fancyapps/fancybox/dist/jquery.fancybox.min.css' %}">
    {% compress css %}
      <link type="text/x-scss" href="{% static 'scss/purpose.scss' %}" rel="stylesheet" media="screen">
        <link rel="stylesheet" href="{% static 'libs/animate.css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'libs/swiper/dist/css/swiper.min.css' %}">
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <!-- HEADER -->
    <header class="header-{% if header_style == 'primary' %}primary{% else %}transparent{% endif %}" id="header-main">
        {% include "header.html" %}
    </header>

    {% block content %}
    {% endblock content %}
    <!-- FEEDBACK BUTTON -->
    <div id="feedback-button"></div>

    <!-- FOOTER -->
    <footer class="footer footer-dark bg-gradient-primary">
        {% include "footer.html" %}
    </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
        <!-- Bootstrap JS and its dependencies-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

        <!-- Panelbear Analytics -->
        <script async src="https://cdn.panelbear.com/analytics.js?site=9TD30771kzW"></script>
        <script>
            window.panelbear = window.panelbear || function(){ window.panelbearQ = window.panelbearQ || []; panelbearQ.push(arguments); };
            panelbear('config', { site: '9TD30771kzW' });
        </script>

        {% compress js %}
            <script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
            <script src="{% static 'libs/svg-injector/dist/svg-injector.min.js' %}"></script>
            <script src="{% static 'js/purpose.js' %}"></script>
            <script src="{% static 'js/purpose.core.js' %}"></script>
            <script src="{% static 'libs/swiper/dist/js/swiper.min.js' %}"></script>
        {% endcompress %}


    {% render_bundle 'feedback_button' %}
    {% render_bundle 'chunk-vendors' %}
    {% endblock javascript %}
  </body>
</html>

healthpat/templates/footer.html
{% load static i18n compress %}
<div class="container">
    <div class="row pt-md">
        <div class="col-lg-4 mb-5 mb-lg-0">
            <a href="{% url 'retail:home' %}">
                <img src="https://res.cloudinary.com/dmuligbfy/image/upload/w_500,h_90,c_fill,g_auto/v1607111107/healthpat/healthpat_white.png" alt="Logo" style="height: 30px;">
            </a>
            <p class="text-sm mt-3">Find prescription medication in Mexico.</p>
        </div>
        <div class="col-lg-2 col-6 col-sm-4 ml-lg-auto mb-5 mb-lg-0">
            <h6 class="heading mb-3"><b>Account</b></h6>
            <ul class="list-unstyled">
                <li><a href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                <li><a href="{% url 'users:register' %}">Sign Up</a>
                </li>
                <li><a href="{% url 'users:login' %}">Sign In</a>
                </li>
            </ul>
        </div>
        <div class="col-lg-2 col-6 col-sm-4 mb-5 mb-lg-0">
            <h6 class="heading mb-3"><b>Company</b></h6>
            <ul class="list-unstyled">
                <li><a href="{% url 'retail:request' %}">Missing Your Prescription?</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="row align-items-center justify-content-md-between py-4 mt-4 delimiter-top">
        <div class="col-md-6">
            <div class="copyright text-sm font-weight-bold text-center text-md-left">
                &copy; 2020 <a href="/" class="font-weight-bold">{{ APP_NAME }}</a>. All rights reserved.
            </div>
        </div>
        <div class="col-md-6">
            <ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
              <li class="nav-item">
                  <a class="nav-link active" href="https://gitlab.com/crawfordleeds/healthpat" target="_blank">
                      <i class="fab fa-gitlab"></i>
                  </a>
              </li>
            </ul>
        </div>
    </div>
</div>

healthpat/templates/header.html
{% load static %}
<!-- Main navbar -->
<nav class="navbar navbar-main navbar-sticky navbar-expand-lg navbar-transparent navbar-dark bg-primary" id="navbar-main">
    <div class="container px-lg-0">
        <a class="navbar-brand mr-lg-5" href="{% url 'retail:home' %}">
            <img class="d-none d-md-block" alt="{{ APP_NAME }}" src="https://res.cloudinary.com/dmuligbfy/image/upload/w_500,h_90,c_fill,g_auto/v1607111107/healthpat/healthpat_white.png" style="height: 25px;"> <!-- Hide full logo on screens smaller than md -->
            <img class="d-md-none" alt="{{ APP_NAME }}" src="https://res.cloudinary.com/dmuligbfy/image/upload/w_500,h_90,c_fill,g_auto/v1607111107/healthpat/healthpat_white.png" style="height: 20px;"> <!-- Show icon on screens smaller than md -->
        </a>

        <!-- Navbar collapse trigger -->
        <button class="navbar-toggler pr-0" type="button" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-main-collapse">

            <ul class="navbar-nav ml-auto">
                <li class="d-none d-lg-block nav-item {% if request.path == '/request/' %}active{% endif %}">
                  <a class="nav-link mr-3" href="{% url 'retail:request' %}">Missing Your Prescription?</a>
                </li>
                {% if request.user.is_authenticated %}
                    <a href="#" class="d-none d-lg-block nav-link" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span>
                            <i class="fa fa-user-circle"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-right dropdown-menu-arrow">
                      <div class="list-group">
                        <a class="dropdown-item" href="{% url 'dashboard:dashboard' %}">My Account</a>
                        <div class="dropdown-divider" role="presentation"></div>
                            <a class="dropdown-item" href="{% url 'users:logout' %}"><span class="mr-2"><i class="fa fa-sign-out-alt"></i></span>Logout</a>
                      </div>
                    </div>
                    <li class="d-block d-lg-none nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}"><span class="mr-2"><i class="fa fa-sign-out-alt"></i></span>Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="d-none d-sm-block btn btn-sm btn-white btn-circle btn-icon">
                            <span class="btn-inner--icon"><i class="fa fa-user-plus"></i></span>
                            <span class="btn-inner--text">Log In / Sign Up</span>
                        </a>
                        <a href="{% url 'users:login' %}" class="d-sm-none btn btn-sm btn-white btn-circle btn-icon">
                            <span class="btn-inner--text">Log In / Sign Up</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>